# Generated by Django 5.0.1 on 2024-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Dillawar', max_length=20),
            preserve_default=False,
        ),
    ]
